### ISSUE TITLE
[Request] Add WindowsPCHealthCheck

### ISSUE THREAD

**Issue by NatoBoram** [ScoopInstaller/Extras#6401]
Not that it's very important to add, lol

At https://www.microsoft.com/en-us/windows/windows-11#pchealthcheck, there's a download button that leads to https://aka.ms/GetPCHealthCheckApp.

Here's its `winget` entry

```yaml
Found Windows PC Health Check [Microsoft.WindowsPCHealthCheck]
Version: 2.3.2106.25001
Publisher: Microsoft Corporation
Description: Check Windows 11 upgrade compatibility.
License: Copyright (c) Microsoft Corporation
Installer:
  Type: Msi
  Locale: en-US
  Download Url: https://download.microsoft.com/download/1/d/d/1dd9969b-bc9a-41bc-8455-bc657c939b47/WindowsPCHealthCheckSetup.msi
  SHA256: 8c905bd1f1e50ead3938bfa4d50c252e4739232a7452971ff1d4f9be1fea5e47
```
